### ISSUE TITLE
Update QC cutoffs for samples to include when building trees and run stringent only

### ISSUE THREAD

**Issue by kmfisch** [ucsd-ccbb/C-VIEW#125]

**Comment by AmandaBirmingham** [comment]
From: "Laurent, Louise" 
Date: Friday, September 24, 2021 at 5:15 PM
Subject: Re: Should sample qc criteria for tree-building and/or variant/epidemiology usability be updated?

As noted by Amanda, the "overall_fail" column takes into account the N-metric, which adds a substantial layer of stringency. My reasoning is this:
•	for return of results into the medical record, we want to be very stringent (so use "overall_fail").
•	for building trees, we can afford to be less stringent (so use "any_fail") and it may be of benefit to include more samples.
Louise
