### ISSUE TITLE
Update pi_from_pileup to 1.0.3 and output entire pi_from_output TSV in addition to just pi metric

### ISSUE THREAD

**Issue by niemasd** [ucsd-ccbb/C-VIEW#126]
Currently, we're only pulling the pi metric from the `pi_from_pileup` output:

https://github.com/ucsd-ccbb/covid_sequencing_analysis_pipeline/blob/5a7493034031d578035a9336aa519fa6834d22c3/pipeline/sarscov2_consensus_pipeline.sh#L121

```bash
echo -e "$SAMPLEID\t"$(pi_from_pileup $WORKSPACE/"$SAMPLEID".trimmed.sorted.pileup.txt | tail -1 | cut -f3) > $WORKSPACE/"$SAMPLEID".pi-metric.tsv
```

However, given that the pi metric is just the average of the heterozygosity score across all positions, Peter is interested in computing a "constrained" pi metric on specific positions of interest (e.g. Pangolin-relevant positions). Also, he's interested in looking at diversity across the genome, which the `pi_from_pileup` output naturally outputs (it first outputs the position + diversity score for all positions of the genome, and *then* it outputs pi).

For now, to avoid having to rerun `pi_from_pileup` on pile-up files (which is quite slow because of the file transfer to download the pile-up file), it would be good if we included the full `pi_from_pileup` output TSV as one of our pipeline output files. We could change the command above as follows:

```bash
pi_from_pileup $WORKSPACE/"$SAMPLEID".trimmed.sorted.pileup.txt > $WORKSPACE/"$SAMPLEID".pi_from_pileup.tsv
echo -e "$SAMPLEID\t"$(cat $WORKSPACE/"$SAMPLEID".pi_from_pileup.tsv | tail -1 | cut -f3) > $WORKSPACE/"$SAMPLEID".pi-metric.tsv
```

Or you could omit the second command entirely, as the `pi_from_pileup` TSV output includes the pi metric in the last line (so your report generation could just pull it from the full TSV output, `$WORKSPACE/"$SAMPLEID".pi_from_pileup.tsv`)

Also, I released a new version of `pi_from_pileup` (1.0.3) in which I delete a debugging print statement. This print statement didn't impact the correctness of the pipeline before (it just added more intermediary lines in the `pi_from_pileup` output, but the last line containing the pi metric itself remained the same), but if we want to output the full `pi_from_pileup` output TSV, we would need to update first

**Comment by AmandaBirmingham** [comment]
Note to self: this will require updating the install of pi_from_pileup on the cluster image
