### ISSUE TITLE
Implement ViReflow to optimize pipeline

### ISSUE THREAD

**Issue by niemasd** [ucsd-ccbb/C-VIEW#99]
I have been developing a tool called [ViReflow](https://github.com/niemasd/ViReflow), which is a Python script that does the following:

* **Input:** Raw sequence data from one sample (`s3` paths to R1 and R2 FASTQ files) and virus parameters (e.g. SARS-CoV-2 reference genome, primers, etc.)
* **Output:** A [Reflow](https://github.com/grailbio/reflow) run file that can be executed as follows: `reflow run <vireflow_out>`

The Reflow run file output by ViReflow includes the steps of the workflow as well as AWS instance minimum specifications (e.g. CPUs, RAM, etc.), and Reflow automatically handles allocating appropriate AWS instances as well as delegating the executions of each step. Importantly, Reflow automatically detects dependencies (and lack thereof) between steps of the workflow, and it automatically executes independent steps in parallel.

ViReflow isn't quite production-ready (I still need to test it), but once I do, we should be able to do something pretty simple like the following (e.g. as a bash command):

* For each sample:
    * Run ViReflow to generate a Reflow run file: `ViReflow.py ...`
    * Execute the Reflow run file: `reflow run ...`

I *think* we should be able to run them all in parallel, e.g. something like the following:

```bash
for sample in $(SAMPLES) ; do ViReflow.py <vireflow_params_for_sample> -o $sample.rf && reflow run $sample.rf > $sample.reflow.log & done
```

The `&` before the `done` will have them run in the background instead of in the foreground, so they'll all run together (it'll probably output a bunch of stuff to standard output for each one, hence redirecting standard output to `$sample.reflow.log`).

**Comment by rob-knight** [comment]
Assuming that ViReflow is really ready to go now, it would be useful to integrate. Check with Niema on whether substantial refactoring is needed after the latest round of benchmarking though.

**Comment by rob-knight** [comment]
Specifically, we would like to see constant-time (or near constant time) performance at least up to 1k sequences, and preferably up to 10k or 100k.

**Comment by niemasd** [comment]
Using ViReflow, 1k samples unfortunately seems to take around 1.5 hours (whereas 100 samples took like 10 minutes), so it doesn't quite work as I expected. It seems to be getting clogged up in the scheduling portion of it.

Given that the external stakeholders want something with a GUI that ideally works cross-platform, we may want to rewrite it in NextFlow, which natively supports AWS, GCP, Azure, local HPC cluster, and local machine without any changes to the pipeline itself. The problem is that I (1) don't know how to create a GUI, and (2) don't know anything about NextFlow (Reflow took quite some time to learn), so I'm not confident I can get something production-ready too soon. We can fortunately leverage the Docker images I created when developing ViReflow regardless of what route we take. Do we happen to know anyone who could provide guidance regarding NextFlow?

Thoughts?

**Comment by niemasd** [comment]
It seems as though Reflow has released a new update ([1.8.0](https://github.com/grailbio/reflow/releases/tag/reflow1.8.0)), and based on the update description, some of the features seem like they may help with this type of thing. I'll try updating as well as a couple of other minor changes I thought of to see if they'll fix the scheduling clog, and if it works, that'll be nice, and if not, we can think of how we want to proceed

**Comment by rob-knight** [comment]
Looks like Carlos Guzman might be a good contact? https://cipher.readthedocs.io/en/latest/

**Comment by niemasd** [comment]
Ah, thanks! I know Carlos, so that works well. I had an idea on how to potentially improve the situation with ViReflow in its current implementation using Reflow, so I'll try that out first, and if it ends up not working (and/or if we still want to pursue something on NextFlow), I'll reach out to him

**Comment by niemasd** [comment]
@AmandaBirmingham I wanted to ping regarding integrating ViReflow into the CCBB pipeline, as @rob-knight suggested that we have the integration implemented prior to submitting the ViReflow manuscript for peer review. Can we make the integration a priority? I'd be happy to help with the heavy lifting however would help the most.

ViReflow now supports all of the following tasks that we currently do in the CCBB pipeline:

* Map reads using Minimap2, including the "truncate at X successfully-mapped reads" feature
* Trim reads using iVar Trim
* Call variants using iVar Variants (but it outputs the variants as a standard VCF rather than the proprietary iVar TSV)
* Generate a consensus sequence (I use BCFTools to generate a consensus sequence from the variants + ref genome)
* Assign lineage using Pangolin (this step is optional)
    * We may want to still do this in bulk on all samples simultaneously rather than on each sample within ViReflow to give us more fine-tuned power over the Pangolin and PangoLEARN versions

**Comment by rob-knight** [comment]
I think an important component is checking that it actually provides performance advantages over current procedure — has this benchmarking been done yet?

Thanks,
Rob

**Comment by niemasd** [comment]
@rob-knight I ran ViReflow on the full AHFGT7DRXY run, and the results were as follows (which are present in the manuscript):
* Overall runtime without capping at 2 million successfully-mapped reads = **2.5 hours**
    * This is the runtime of the longest sample(s): most samples finished running long before this
    * Also, I now have the "cap at N successfully-mapped reads" feature implemented, so this will be even smaller
* Overall EC2 cost without capping at 2 million successfully-mapped reads = **$59.04** = **$0.086/sample**
    * With the "cap at N successfully-mapped reads" feature implemented, this will also decrease (but not as drastically as runtime)

And as far as accuracy is concerned, Pangolin lineages match the original pipeline (sequences were identical in all cases I checked, given that it's the same exact toolset; we're just changing how they're being executed)

**Comment by AmandaBirmingham** [comment]
Wow, is that 2.5 hours including the tree building steps?

**Comment by niemasd** [comment]
@AmandaBirmingham Ah no sorry, just for mapping, trimming, variant calling, and generating consensus sequence. This would swap in for Steps 1-7 of [`sarscov2_consensus_pipeline.sh`](pipeline/sarscov2_consensus_pipeline.sh)

**Comment by AmandaBirmingham** [comment]
@niemasd Ah, gotcha.  Assuming @rob-knight  approves, could you run vireflow capped at 2 million reads on the sequencing run at s3://ucsd-all/210730_A00953_0364_BHGYJ7DSX2/210730_A00953_0364_BHGYJ7DSX2_fastq/ ?  This will allow us to show how much faster vireflow is, since I have timing info for approximately equivalent steps on that dataset with that read cap on the current pipeline.

**Comment by rob-knight** [comment]
Approve — this comparison is essential. Thanks!

**Comment by niemasd** [comment]
Sounds great! I just generated the Reflow run files, and I'll kick it off shortly

**Comment by rob-knight** [comment]
Thanks!

**Comment by rob-knight** [comment]
Thanks, Amanda how does this compare to your run on same data?

**Comment by AmandaBirmingham** [comment]
For the run of the s3://ucsd-all/210730_A00953_0364_BHGYJ7DSX2/210730_A00953_0364_BHGYJ7DSX2_fastq/ data capped at 2 million reads, we kicked the pipeline off at 2:03 pm and the last set of processed per-sample files was uploaded to S3 at 3:19 pm, giving us a time of about 1.26 hours for the 2607 samples. 

This was done using *up to* 20 r5d.24xlarge compute nodes (I don't have exact details for how many of these nodes were used for how much of the total time, as unused nodes spin down after they run out of jobs. Katie *might* be able to pull that info when she returns ...).  These were used in on-demand mode, and are currently $6.912/hr (billed per-second for partial hours), so I estimate the maximum that it could have cost is $174.18 ($6.912/hr/node * 20 nodes * 1.26 hrs).

**Comment by niemasd** [comment]
Thank you, Amanda! I'm rerunning with the `Undetermined` samples removed to get a tighter fit of my runtime, but it seems fairly similar. Does this runtime also include transferring the samples to the S3 bucket?

**Comment by AmandaBirmingham** [comment]
The runtime above does not include time to transfer samples’ raw fastq.gz files to S3, only the time to upload samples’ processed results from the compute nodes where they are generated onto S3.

**Comment by niemasd** [comment]
@AmandaBirmingham Thanks for clarifying! I was unclear: my time also does not include the time it takes to transfer the raw `fastq.gz` files *to* S3 (as that can vary significantly and is upstream of analysis). It only includes processing time on the compute node + transfer of output files from compute node to S3, which seems to be precisely what your numbers are timing as well, so it seems as though they are indeed apples-to-apples

@rob-knight I re-ran ViReflow on `s3://ucsd-all/210730_A00953_0364_BHGYJ7DSX2/210730_A00953_0364_BHGYJ7DSX2_fastq/` but with the `Undetermined` samples removed, and the runtime was 4143.775 seconds = 1.15 hours. But this *doesn't* include the QC stuff that CCBB runs. Thus, with that taken into account, it seems as though the runtimes are essentially equal, plus or minus stochasticity

**Comment by AmandaBirmingham** [comment]
@niemasd do you have cost info for the ViReflow run on `s3://ucsd-all/210730_A00953_0364_BHGYJ7DSX2/210730_A00953_0364_BHGYJ7DSX2_fastq/`?

**Comment by niemasd** [comment]
@AmandaBirmingham I unfortunately can't pull it without the cost spreadsheet that @kmfisch generates. I'll get it to you once she's back, though!

**Comment by niemasd** [comment]
@AmandaBirmingham @rob-knight I just got the most recent cost spreadsheet from @kmfisch, so I have the updated runtime + cost from running `BHGYJ7DSX2` with the `Undetermined` files removed and with the 2 million successfully-mapped reads cap:
* Total Runtime = 4143.775 seconds = 69.1 minutes = 1.15 hours
* Total Cost (USD) = $117.48

**Comment by kmfisch** [comment]
@niemasd since you have the spreadsheet, are you able to pull the exact cost for Amanda's run? @AmandaBirmingham will probably need to tell you the day it was run?

**Comment by niemasd** [comment]
@kmfisch Yes, if you give me the instance IDs and day, assuming those specific instances were not used for anything else that day, I can pull the total cost of Amanda's run as well

**Comment by kmfisch** [comment]
@AmandaBirmingham can you please provide the day this was run? i can help with the instance types, but @niemasd unless it was your instances, nothing else would have been running

**Comment by AmandaBirmingham** [comment]
CCBB processing of sequencing run 210730_A00953_0364_BHGYJ7DSX2 was done on 2021-08-02.  Note that this was a complete pipeline run (per-sample trimming/mapping/variant calling/various metric calculating, per-sequencing-run qc calulations, cumulative lineage calling, and cumulative tree building).  Not sure exactly how you want to account for that in the cost calculations ... I know that the qc calculations, lineage calling, and tree building all happen on a single compute node, so when the time at which the cluster scales down to a single compute node is approximately the time we finish per-sample processing ....

**Comment by kmfisch** [comment]
Ah ha, ok well then maybe not worth the effort of pulling. Thanks for the details!

**Comment by niemasd** [comment]
I don't think we're doing this anymore, so I'll go ahead and close this issue. Please feel free to reopen if I'm misemembering
